version: '3.8'

networks:
  dev-network:
    driver: bridge

services:
  dev-db:
    image: postgres:16.1-alpine3.19
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - dev-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - dev-db
    networks:
      - dev-network
